/**
 * Standardized Machine-Readable Error Codes
 */
export enum ErrorCodes {
  // Client & Validation
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',

  // Authentication & Authorization
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',

  // Domain & Game Logic
  DOMAIN_ERROR = 'DOMAIN_ERROR',
  OUT_OF_RANGE = 'OUT_OF_RANGE',
  SPAWN_NOT_ACTIVE = 'SPAWN_NOT_ACTIVE',
  SPAWN_EXPIRED = 'SPAWN_EXPIRED',
  ALREADY_CLAIMED = 'ALREADY_CLAIMED',
  CLAIM_LIMIT_REACHED = 'CLAIM_LIMIT_REACHED',
  COOLDOWN_ACTIVE = 'COOLDOWN_ACTIVE',

  // System & Infrastructure
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
}
